-- PPT 9번 M:N 관계 예시 문제

-- 학생테이블
CREATE TABLE STUDENT (
    STU_NO NUMBER PRIMARY KEY,
    STU_NAME VARCHAR2(20) NOT NULL,
    STU_AGE NUMBER(3)
);

-- 과목테이블
CREATE TABLE SUBJECT (
    SUB_CODE CHAR(1) PRIMARY KEY,
    SUB_NAME VARCHAR2(20) NOT NULL,
    SUB_PROF VARCHAR2(20)
);

-- 수강신청테이블
CREATE TABLE ENROLL (
    EN_NO NUMBER PRIMARY KEY,
    STU_NO NUMBER REFERENCES STUDENT(STU_NO),
    SUB_CODE CHAR(1) REFERENCES SUBJECT(SUB_CODE)
);


-- 삭제
DROP TABLE ENROLL;  -- 외래키를 가진 테이블을 먼저 제거할 수 있다.
DROP TABLE SUBJECT;
DROP TABLE STUDENT;
