-- 실습.
-- 테이블 : MEMBERS
-- 1. 회원번호 : NO, NUMBER, 기본키
-- 2. 회원아이디 : ID, VARCHAR2(30), 필수, 중복불가
-- 3. 회원비밀번호 : PW, VARCHAR2(30), 필수
-- 4. 회원포인트 : POINT, NUMBER, 기본값 [1000] (기본값은 제약조건:CONSTRAINT 는 아니다.)
-- 5. 회원등급 : GRADE, VARCHAR2(10), 'VIP', 'GOLD', 'SILVER', 'BRONZE' 중 하나만 가질 수 있다.
-- 6. 회원이메일 : EMAIL, VARCHAR2(100), 중복불가

/**** 제약조건의 이름을 주는 방법 *****
CREATE TABLE MEMBERS (
    NO NUMBER,
        CONSTRAINT MEMBERS_PK PRIMARY KEY(NO),
    ID VARCHAR2(30) 
        CONSTRAINT ID_NN NOT NULL 
        CONSTRAINT ID_UQ UNIQUE,
    PW VARCHAR2(30) 
        CONSTRAINT PW_NN NOT NULL,
    POINT NUMBER DEFAULT 1000,
    GRADE VARCHAR2(10) 
        CONSTRAINT GRADE_CK CHECK(GRADE IN('VIP', 'GOLD', 'SILVER', 'BRONZE')),
    EMAIL VARCHAR2(100) 
        CONSTRAINT EMAIL_UQ UNIQUE
);
*/

CREATE TABLE MEMBERS (
    NO NUMBER PRIMARY KEY,
    ID VARCHAR2(30) NOT NULL UNIQUE,
    PW VARCHAR2(30) NOT NULL,
    POINT NUMBER DEFAULT 1000,
    GRADE VARCHAR2(10) CHECK(GRADE IN('VIP', 'GOLD', 'SILVER', 'BRONZE')),
    EMAIL VARCHAR2(100) UNIQUE
);

-- 칼럼 수정하기

-- 1. 새로운 칼럼 추가하기
ALTER TABLE MEMBERS ADD ADDRESS VARCHAR2(100) NOT NULL;
ALTER TABLE MEMBERS ADD JOINDATE DATE;

-- 2. 기존 칼럼 삭제하기
ALTER TABLE MEMBERS DROP COLUMN ADDRESS;

-- 3. 기존 칼럼의 타입 변경하기
ALTER TABLE MEMBERS MODIFY GRADE VARCHAR2(20);  -- GRADE 칼럼의 VARCHAR2(10) -> VARCHAR2(20)으로 변경, CHECK 조건은 그대로 유지됨

-- 4. 기존 칼럼의 이름 바꾸기
ALTER TABLE MEMBERS RENAME COLUMN JOINDATE TO REGDATE;  -- JOINDATE 를 REGDATE 로 변경


-- MEMBERS 테이블 구조 확인하기
DESC MEMBERS;
