-- PPT 11번. DDL 활용 연습문제


-- 테이블 삭제
DROP TABLE SCHEDULE;
DROP TABLE PLAYER;
DROP TABLE EVENT;
DROP TABLE NATION;


-- 1. NATION 테이블 생성
CREATE TABLE NATION (
    N_CODE NUMBER(3) PRIMARY KEY,
    N_NAME VARCHAR2(30) NOT NULL,
    N_PARTI_PERSON NUMBER DEFAULT 0,
    N_PARTI_EVENT NUMBER,
    N_PREV_RANK NUMBER,
    N_CURR_RANK NUMBER
);


-- 2. EVENT 테이블 생성
CREATE TABLE EVENT (
    E_CODE NUMBER PRIMARY KEY,
    E_NAME VARCHAR2(30) NOT NULL,
    E_FIRST_YEAR NUMBER(4),
    E_INFO VARCHAR2(100)
);


-- 3. PLAYER 테이블
CREATE TABLE PLAYER (
    P_CODE NUMBER(3) PRIMARY KEY,
    P_NAME VARCHAR2(30) NOT NULL,
    N_CODE NUMBER(3) REFERENCES NATION(N_CODE),
    E_CODE NUMBER REFERENCES EVENT(E_CODE),
    P_RANK NUMBER,
    P_AGE NUMBER(3)
);


-- 4. SCHEDULE 테이블
CREATE TABLE SCHEDULE (
    N_CODE NUMBER(3) REFERENCES NATION(N_CODE),
    E_CODE NUMBER REFERENCES EVENT(E_CODE),
    S_START_DATE DATE,
    S_END_DATE DATE,
    S_INFO VARCHAR2(100),
    PRIMARY KEY (N_CODE, E_CODE)  -- 2개 이상의 칼럼의 집합으로 기본키를 생성할 수 있다.
);
