-- 테이블 삭제
DROP TABLE CUSTOMER;
DROP TABLE BANK;

-- BANK 테이블 생성
CREATE TABLE BANK (
    BANK_CODE VARCHAR2(20),
    CONSTRAINT BANK_PK PRIMARY KEY(BANK_CODE),  --  기존 제약조건명 SYS_XXXXXX 로 저장하지 않고, BANK_PK 라는 이름의 제약조건을 준다.
    BANK_NAME VARCHAR2(30)
);

-- BANK 테이블의 제약조건을 확인해보자.
SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'BANK';

-- customer 테이블 생성
CREATE TABLE CUSTOMER (
    NO NUMBER,
        CONSTRAINT CUSTOMER_PK PRIMARY KEY(NO),
    NAME VARCHAR2(30)
        CONSTRAINT NAME_NN NOT NULL,
    PHONE VARCHAR2(30)
        CONSTRAINT PHONE_UQ UNIQUE,
    AGE NUMBER 
        CONSTRAINT AGE_CK CHECK(AGE BETWEEN 0 AND 100),
    BANK_CODE VARCHAR2(20),
        CONSTRAINT CUSTOMER_BANK_FK FOREIGN KEY(BANK_CODE) REFERENCES BANK(BANK_CODE)
);

-- CUSTOMER 테이블의 제약조건을 확인해보자.
SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'CUSTOMER';



-- 제약조건 수정

-- 1. 제약조건의 삭제
ALTER TABLE CUSTOMER DROP CONSTRAINT CUSTOMER_PK;

-- 2. 제약조건의 추가
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_PK PRIMARY KEY(NO);

-- 3. 제약조건의 비활성화 (끄기)
ALTER TABLE CUSTOMER DISABLE CONSTRAINT CUSTOMER_PK;

-- 4. 제약조건의 활성화 (켜기)
ALTER TABLE CUSTOMER ENABLE CONSTRAINT CUSTOMER_PK;