-- PPT 12번. 예제 데이터베이스 생성

-- 테이블 삭제
DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;


-- 1. DEPARTMENT 테이블 생성
CREATE TABLE DEPARTMENT (
    DEPT_NO NUMBER PRIMARY KEY,
    DEPT_NAME VARCHAR2(15) NOT NULL,
    LOCATION VARCHAR2(15) NOT NULL
);

-- 2. EMPLOYEE 테이블 생성
CREATE TABLE EMPLOYEE (
    EMP_NO NUMBER DEFAULT 1001 PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    DEPART NUMBER REFERENCES DEPARTMENT(DEPT_NO),  -- 외래키는 다른 테이블의 기본키(또는 UNIQUE 칼럼)을 참조할 수 있다.)
    POSITION VARCHAR2(20),
    GENDER CHAR(2),
    HIRE_DATE DATE,
    SALARY NUMBER
);


-- 테이블에 데이터 추가하기
-- INSERT INTO 테이블 (칼럼1, 칼럼2, ...) VALUES (값1, 값2, ...);
-- INSERT INTO 테이블 VALUES (값1, 값2, ...);

-- 데이터의 추가도 테이블의 추가 순서와 같다.
-- 부모 테이블 먼저 추가. 자식 테이블 나중에 추가.

-- 1. DEPARTMENT 테이블에 데이터 추가하기
INSERT INTO DEPARTMENT (DEPT_NO, DEPT_NAME, LOCATION) VALUES (1, '총무부', '101호');
INSERT INTO DEPARTMENT (DEPT_NO, DEPT_NAME, LOCATION) VALUES (2, '인사부', '601호');
INSERT INTO DEPARTMENT (DEPT_NO, DEPT_NAME, LOCATION) VALUES (3, '자재부', '301호');


-- 2. EMPLOYEE 테이블에 데이터 추가하기
INSERT INTO EMPLOYEE (EMP_NO, NAME, DEPART, POSITION, GENDER, HIRE_DATE, SALARY) 
VALUES (1001, '에밀리', 1, '과장', 'F', '98/12/20', 5000000);
INSERT INTO EMPLOYEE (EMP_NO, NAME, DEPART, POSITION, GENDER, HIRE_DATE, SALARY) 
VALUES (1002, '제임스', 1, '대리', 'M', '00/12/20', 3500000);
INSERT INTO EMPLOYEE (EMP_NO, NAME, DEPART, POSITION, GENDER, HIRE_DATE, SALARY) 
VALUES (1003, '사만다', 2, '사원', 'F', '15/12/20', 2000000);
INSERT INTO EMPLOYEE (EMP_NO, NAME, DEPART, POSITION, GENDER, HIRE_DATE, SALARY) 
VALUES (1004, '데이빗', 3, '부장', 'M', '95/12/20', 6500000);

-- 3. 실제로 저장하기 (INSERT, UPDATE, DELETE 문은 COMMIT 이 필요하다.)
COMMIT
